// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.sportSchema;

[PrimaryKey("Coach_Id", "TrainingPlan_Id", "ValidFrom", "ValidTo")]
[Table("CoachTrainingPlan", Schema = "sport")]
[Index("Coach_Id", "ValidFrom", "ValidTo", Name = "IX_CoachTraining_Coach_Date")]
[Index("TrainingPlan_Id", "ValidFrom", "ValidTo", Name = "IX_CoachTraining_Training_Date")]
public partial class CoachTrainingPlan
{
    [Key]
    public int Coach_Id { get; set; }

    [Key]
    public int TrainingPlan_Id { get; set; }

    [Key]
    public DateOnly ValidFrom { get; set; }

    [Key]
    public DateOnly ValidTo { get; set; }

    [ForeignKey("Coach_Id")]
    [InverseProperty("CoachTrainingPlans")]
    public virtual Coach Coach { get; set; } = null!;

    [ForeignKey("TrainingPlan_Id")]
    [InverseProperty("CoachTrainingPlans")]
    public virtual TrainingPlan TrainingPlan { get; set; } = null!;
}