// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.sportSchema;

[PrimaryKey("Coach_Id", "Training_Id", "ParticipationType_Id")]
[Table("CoachTraining", Schema = "sport")]
public partial class CoachTraining
{
    [Key]
    public int Coach_Id { get; set; }

    [Key]
    public int Training_Id { get; set; }

    [Key]
    public int ParticipationType_Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public required string Note { get; set; }

    [ForeignKey("Coach_Id")]
    [InverseProperty("CoachTrainings")]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual Coach Coach { get; set; } = null!;

    [ForeignKey("ParticipationType_Id")]
    [InverseProperty("CoachTrainings")]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual ParticipationType ParticipationType { get; set; } = null!;

    [ForeignKey("Training_Id")]
    [InverseProperty("CoachTrainings")]
    public virtual Training Training { get; set; } = null!;
}