// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.sportSchema;

[PrimaryKey("Coach_Id", "TrainingEntitlement_Id", "CoachRole_Id")]
[Table("CoachTrainingEntitlement", Schema = "sport")]
public partial class CoachTrainingEntitlement
{
    [Key]
    public int Coach_Id { get; set; }

    [Key]
    public int TrainingEntitlement_Id { get; set; }

    [Key]
    public int CoachRole_Id { get; set; }

    [ForeignKey("Coach_Id")]
    [InverseProperty("CoachTrainingEntitlementCoaches")]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual Coach Coach { get; set; } = null!;

    [ForeignKey("CoachRole_Id")]
    [InverseProperty("CoachTrainingEntitlementCoachRoles")]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual CoachRole CoachRole { get; set; } = null!;

    [ForeignKey("TrainingEntitlement_Id")]
    [InverseProperty("CoachTrainingEntitlements")]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual TrainingEntitlement TrainingEntitlement { get; set; } = null!;
}