// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NetTopologySuite.Geometries;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.sportSchema;

[Table("IceRink", Schema = "sport")]
public partial class IceRink
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string Name { get; set; } = null!;

    [StringLength(200)]
    public string Address { get; set; } = null!;

    [StringLength(100)]
    public string City { get; set; } = null!;

    public Geometry? Location { get; set; }

    [InverseProperty("IceRink")]
    public virtual ICollection<Match> Matches { get; set; } = new List<Match>();

    [InverseProperty("IceRink")]
    public virtual ICollection<Training> Trainings { get; set; } = new List<Training>();

    [InverseProperty("HomeIceRink")]
    public virtual ICollection<Opponent> Opponents { get; set; } = new List<Opponent>();
}