// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.sportSchema;

[Table(nameof(Match), Schema = Schemas.Sport)]
public partial class Match
{
    [Key]
    public int Id { get; set; }

    public int Season_Id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public required string SeasonCategory_Name { get; set; }

    public int IceRink_Id { get; set; }

    public DateOnly Date { get; set; }

    [Precision(0)]
    public TimeOnly TimeFrom { get; set; }

    [Precision(0)]
    public TimeOnly TimeTo { get; set; }

    public int? DurationMinutes { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public required string Note { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string? MatchCode { get; set; }

    public int Opponent_Id { get; set; }

    public bool IsHome { get; set; }

    public byte? GoalsScored { get; set; }

    public byte? GoalsConceded { get; set; }

    public int MatchType_Id { get; set; }

    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual IceRink IceRink { get; set; } = null!;

    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual MatchType MatchType { get; set; } = null!;

    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual Opponent Opponent { get; set; } = null!;

    [ForeignKey(nameof(Season_Id))]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual Season Season { get; set; } = null!;

    [ForeignKey(nameof(Season_Id) + ", " + nameof(SeasonCategory_Name))]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual SeasonCategory SeasonCategory { get; set; } = null!;
}