// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.sportSchema;

[Table("Match", Schema = "sport")]
public partial class Match
{
    [Key]
    public int Id { get; set; }

    public int Season_Id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string SeasonCategory_Name { get; set; } = null!;

    public int IceRink_Id { get; set; }

    public DateOnly Date { get; set; }

    [Precision(0)]
    public TimeOnly TimeFrom { get; set; }

    [Precision(0)]
    public TimeOnly TimeTo { get; set; }

    public int? DurationMinutes { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Note { get; set; } = null!;

    [StringLength(10)]
    [Unicode(false)]
    public string? MatchCode { get; set; }

    public int Opponent_Id { get; set; }

    public bool IsHome { get; set; }

    public byte? GoalsScored { get; set; }

    public byte? GoalsConceded { get; set; }

    public int MatchType_Id { get; set; }

    [ForeignKey("IceRink_Id")]
    [InverseProperty("Matches")]
    public virtual IceRink IceRink { get; set; } = null!;

    [ForeignKey("MatchType_Id")]
    [InverseProperty("Matches")]
    public virtual MatchType MatchType { get; set; } = null!;

    [ForeignKey("Opponent_Id")]
    [InverseProperty("Matches")]
    public virtual Opponent Opponent { get; set; } = null!;

    [ForeignKey("Season_Id")]
    [InverseProperty("Matches")]
    public virtual Season Season { get; set; } = null!;

    [ForeignKey("Season_Id, SeasonCategory_Name")]
    [InverseProperty("Matches")]
    public virtual SeasonCategory SeasonCategory { get; set; } = null!;
}