// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.sportSchema;

[Table("Opponent", Schema = "sport")]
public partial class Opponent
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public required string Name { get; set; }

    [StringLength(200)]
    public required string Address { get; set; }

    [StringLength(100)]
    public required string City { get; set; }

    public int? HomeIceRink_Id { get; set; }

    [ForeignKey("HomeIceRink_Id")]
    [InverseProperty("Opponents")]
    public virtual IceRink? HomeIceRink { get; set; }

    [InverseProperty("Opponent")]
    public virtual ICollection<Match> Matches { get; set; } = new List<Match>();
}