// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.sportSchema;

[PrimaryKey("Season_Id", "Name")]
[Table("SeasonCategory", Schema = "sport")]
public partial class SeasonCategory
{
    [Key]
    public int Season_Id { get; set; }

    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string Name { get; set; } = null!;

    public int Order { get; set; }

    [StringLength(4000)]
    public string BirthYears { get; set; } = null!;

    [InverseProperty("SeasonCategory")]
    public virtual ICollection<Match> Matches { get; set; } = new List<Match>();

    [ForeignKey("Season_Id")]
    [InverseProperty("SeasonCategories")]
    public virtual Season Season { get; set; } = null!;

    [InverseProperty("SeasonCategory")]
    public virtual ICollection<Training> Training { get; set; } = new List<Training>();

    [InverseProperty("SeasonCategory")]
    public virtual ICollection<TrainingEntitlement> TrainingEntitlements { get; set; } = new List<TrainingEntitlement>();

    [InverseProperty("SeasonCategory")]
    public virtual ICollection<TrainingPlan> TrainingPlans { get; set; } = new List<TrainingPlan>();
}