// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.sportSchema;

[Table(nameof(Training), Schema = Schemas.Sport)]
public partial class Training
{
    [Key]
    public int Id { get; set; }

    public int Season_Id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public required string SeasonCategory_Name { get; set; }

    public int TrainingType_Id { get; set; }

    public int TrainingPhase_Id { get; set; }

    public int TrainingState_Id { get; set; }

    public int? TrainingPlan_Id { get; set; }

    public int IceRink_Id { get; set; }

    [Precision(0)]
    public TimeOnly TimeFrom { get; set; }

    [Precision(0)]
    public TimeOnly TimeTo { get; set; }

    public DateOnly Date { get; set; }

    public int? DurationMinutes { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public required string Note { get; set; }

    [ForeignKey(nameof(Season_Id))]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual Season Season { get; set; } = null!;

    [ForeignKey(nameof(Season_Id) + ", " + nameof(SeasonCategory_Name))]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual SeasonCategory SeasonCategory { get; set; } = null!;

    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual IceRink IceRink { get; set; } = null!;

    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual TrainingPhase TrainingPhase { get; set; } = null!;

    public virtual TrainingPlan? TrainingPlan { get; set; }

    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual TrainingState TrainingState { get; set; } = null!;

    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual TrainingType TrainingType { get; set; } = null!;

    public virtual ICollection<CoachTraining> CoachTrainings { get; set; } = new List<CoachTraining>();
}