// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.sportSchema;

[Table("TrainingEntitlement", Schema = "sport")]
public partial class TrainingEntitlement
{
    [Key]
    public int Id { get; set; }

    public int Season_Id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public required string SeasonCategory_Name { get; set; }

    public int TrainingType_Id { get; set; }

    public int TrainingPhase_Id { get; set; }

    public DateOnly From { get; set; }

    public DateOnly To { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal DurationHours { get; set; }

    [InverseProperty("TrainingEntitlement")]
    public virtual ICollection<CoachTrainingEntitlement> CoachTrainingEntitlements { get; set; } = new List<CoachTrainingEntitlement>();

    [ForeignKey("Season_Id, SeasonCategory_Name")]
    [InverseProperty("TrainingEntitlements")]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual SeasonCategory SeasonCategory { get; set; } = null!;

    [ForeignKey("TrainingPhase_Id")]
    [InverseProperty("TrainingEntitlements")]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual TrainingPhase TrainingPhase { get; set; } = null!;

    [ForeignKey("TrainingType_Id")]
    [InverseProperty("TrainingEntitlements")]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual TrainingType TrainingType { get; set; } = null!;
}