// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.sportSchema;

[Table("TrainingPlan", Schema = "sport")]
public partial class TrainingPlan
{
    [Key]
    public int Id { get; set; }

    public int Season_Id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public required string SeasonCategory_Name { get; set; }

    public int TrainingType_Id { get; set; }

    public int TrainingPhase_Id { get; set; }

    public DateOnly From { get; set; }

    public DateOnly To { get; set; }

    [StringLength(100)]
    public required string Location { get; set; }

    [Precision(0)]
    public TimeOnly TimeFrom { get; set; }

    [Precision(0)]
    public TimeOnly TimeTo { get; set; }

    public int? DurationMinutes { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public required string DayName { get; set; }

    [InverseProperty("TrainingPlan")]
    public virtual ICollection<CoachTrainingPlan> CoachTrainingPlans { get; set; } = new List<CoachTrainingPlan>();

    [ForeignKey("Season_Id, SeasonCategory_Name")]
    [InverseProperty("TrainingPlans")]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual SeasonCategory SeasonCategory { get; set; } = null!;

    [InverseProperty("TrainingPlan")]
    public virtual ICollection<Training> Training { get; set; } = new List<Training>();

    [ForeignKey("TrainingPhase_Id")]
    [InverseProperty("TrainingPlans")]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual TrainingPhase TrainingPhase { get; set; } = null!;

    [ForeignKey("TrainingType_Id")]
    [InverseProperty("TrainingPlans")]
    [DeleteBehavior(DeleteBehavior.ClientSetNull)]
    public virtual TrainingType TrainingType { get; set; } = null!;
}