// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.dboSchema;

[Table("CoachRole")]
public partial class CoachRole
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; } = null!;

    [InverseProperty("CoachRole")]
    public virtual ICollection<CoachTrainingEntitlement> CoachTrainingEntitlementCoachRoles { get; set; } = new List<CoachTrainingEntitlement>();
}