// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;


namespace SportSys.Database.Models.dboSchema;

[Table("Coach")]
public partial class Coach
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; } = null!;

    [StringLength(50)]
    public string LastName { get; set; } = null!;

    [StringLength(101)]
    public string FullName { get; set; } = null!;

    [InverseProperty("Coach")]
    public virtual ICollection<CoachTrainingEntitlement> CoachTrainingEntitlementCoaches { get; set; } = new List<CoachTrainingEntitlement>();

    [InverseProperty("Coach")]
    public virtual ICollection<CoachTrainingPlan> CoachTrainingPlans { get; set; } = new List<CoachTrainingPlan>();

    [InverseProperty("Coach")]
    public virtual ICollection<CoachTraining> CoachTrainings { get; set; } = new List<CoachTraining>();
}