// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportSys.Database.Context;

#nullable disable

namespace SportSys.Database.Migrations
{
    [DbContext(typeof(SportSysDbContext))]
    [Migration("20251127124827_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportSys.Database.Models.Emr.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AllowAnonymousReservations")
                        .HasColumnType("bit");

                    b.Property<bool?>("AllowExternalReservations")
                        .HasColumnType("bit");

                    b.Property<bool?>("AllowExternalUserReservations")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ConfirmDate")
                        .HasColumnType("datetime");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("EnableReservation")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHiddenForSearch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShuttleOnly")
                        .HasColumnType("bit");

                    b.Property<string>("LockReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime");

                    b.Property<short?>("MaxReservations")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteColor")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("Room_id");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeTo")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UnlockTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Block", "plan");
                });

            modelBuilder.Entity("SportSys.Database.Models.Emr.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmbulatoryBookNumber")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<int?>("BlockId")
                        .HasColumnType("int")
                        .HasColumnName("Block_id");

                    b.Property<DateTime?>("FinalDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime");

                    b.Property<string>("InsuranceCompanyCode")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("InsuranceCompany_code");

                    b.Property<decimal?>("InsurancePrice")
                        .HasColumnType("money");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExternalBonus")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsIcBilled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRearranged")
                        .HasColumnType("bit");

                    b.Property<int?>("JobDoneId")
                        .HasColumnType("int")
                        .HasColumnName("JobDone_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Part")
                        .HasColumnType("smallint");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("Patient_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<decimal>("PriceFull")
                        .HasColumnType("money");

                    b.Property<string>("PriceNote")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly?>("TimeArrival")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeTo")
                        .HasColumnType("time");

                    b.Property<int?>("Urgency")
                        .HasColumnType("int");

                    b.Property<string>("UrlOnlineMeeting")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.ToTable("Task", "plan");
                });

            modelBuilder.Entity("SportSys.Database.Models.Emr.Task", b =>
                {
                    b.HasOne("SportSys.Database.Models.Emr.Block", "Block")
                        .WithMany("Tasks")
                        .HasForeignKey("BlockId");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("SportSys.Database.Models.Emr.Block", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
