// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using SportSys.Database.Context;

#nullable disable

namespace SportSys.Database.Migrations
{
    [DbContext(typeof(SportSysDbContext))]
    [Migration("20260526092117_SeasonCategory_AddCompetitionTeamName")]
    partial class SeasonCategory_AddCompetitionTeamName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SportEventSeq", "sport");

            modelBuilder.Entity("SportSys.Database.Models.dboSchema.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)")
                        .HasComputedColumnSql("(([FirstName]+N' ')+[LastName])", true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Coach", "dbo");
                });

            modelBuilder.Entity("SportSys.Database.Models.dboSchema.CoachRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CoachRole", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hlavní"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Asistent"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Obránci"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gólmani"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fyzio"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kondiční"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.CoachTraining", b =>
                {
                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("", "DF_CoachTraining_Note");

                    b.HasKey("CoachId", "TrainingId", "ParticipationTypeId");

                    b.ToTable("CoachTraining", "sport", t =>
                        {
                            t.Property("CoachId")
                                .HasColumnName("Coach_Id");

                            t.Property("TrainingId")
                                .HasColumnName("Training_Id");

                            t.Property("ParticipationTypeId")
                                .HasColumnName("ParticipationType_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.CoachTrainingEntitlement", b =>
                {
                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingEntitlementId")
                        .HasColumnType("int");

                    b.Property<int>("CoachRoleId")
                        .HasColumnType("int");

                    b.HasKey("CoachId", "TrainingEntitlementId", "CoachRoleId");

                    b.ToTable("CoachTrainingEntitlement", "sport", t =>
                        {
                            t.Property("CoachId")
                                .HasColumnName("Coach_Id");

                            t.Property("TrainingEntitlementId")
                                .HasColumnName("TrainingEntitlement_Id");

                            t.Property("CoachRoleId")
                                .HasColumnName("CoachRole_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.CoachTrainingPlan", b =>
                {
                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("CoachId", "TrainingPlanId", "ValidFrom", "ValidTo");

                    b.HasIndex(new[] { "CoachId", "ValidFrom", "ValidTo" }, "IX_CoachTraining_Coach_Date");

                    b.HasIndex(new[] { "TrainingPlanId", "ValidFrom", "ValidTo" }, "IX_CoachTraining_Training_Date");

                    b.ToTable("CoachTrainingPlan", "sport", t =>
                        {
                            t.Property("CoachId")
                                .HasColumnName("Coach_Id");

                            t.Property("TrainingPlanId")
                                .HasColumnName("TrainingPlan_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.IceRink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Geometry>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("", "DF_IceRink_ZipCode");

                    b.HasKey("Id");

                    b.ToTable("IceRink", "sport");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(NEXT VALUE FOR [sport].[SportEventSeq])", "DF_Match_Id");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int>("IceRinkId")
                        .HasColumnType("int");

                    b.Property<string>("MatchCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("MatchTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SeasonCategoryName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.HasKey("Id");

                    b.ToTable("Match", "sport", t =>
                        {
                            t.Property("AwayTeamId")
                                .HasColumnName("AwayTeam_Id");

                            t.Property("HomeTeamId")
                                .HasColumnName("HomeTeam_Id");

                            t.Property("IceRinkId")
                                .HasColumnName("IceRink_Id");

                            t.Property("MatchTypeId")
                                .HasColumnName("MatchType_Id");

                            t.Property("SeasonCategoryName")
                                .HasColumnName("SeasonCategory_Name");

                            t.Property("SeasonId")
                                .HasColumnName("SeasonCategory_Season_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.MatchType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MatchType", "sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ligový zápas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Příprava"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Turnaj"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.ParticipationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ParticipationType", "sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Účast"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bez reakce"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Neúčast"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Spojený trénink"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Neúčast - jiný trénink"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Season", "sport");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.SeasonCategory", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("BirthYears")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasDefaultValue("[]", "DF_SeasonCategory_BirthYears");

                    b.Property<string>("CompetitionCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("", "DF_SeasonCategory_CompetitionCode");

                    b.Property<string>("CompetitionTeamName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("", "DF_SeasonCategory_CompetitionTeamName");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("SeasonId", "Name");

                    b.ToTable("SeasonCategory", "sport", t =>
                        {
                            t.Property("SeasonId")
                                .HasColumnName("Season_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("HomeIceRinkId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Team", "sport", t =>
                        {
                            t.Property("HomeIceRinkId")
                                .HasColumnName("HomeIceRink_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(NEXT VALUE FOR [sport].[SportEventSeq])", "DF_Training_Id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DurationMinutes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(datediff(minute,[TimeFrom],[TimeTo]))", true);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SeasonCategoryName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("TimeTo")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<int>("TrainingPhaseId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainingPlanId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingStateId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Training", "sport", t =>
                        {
                            t.Property("SeasonCategoryName")
                                .HasColumnName("SeasonCategory_Name");

                            t.Property("SeasonId")
                                .HasColumnName("SeasonCategory_Season_Id");

                            t.Property("TrainingPhaseId")
                                .HasColumnName("TrainingPhase_Id");

                            t.Property("TrainingPlanId")
                                .HasColumnName("TrainingPlan_Id");

                            t.Property("TrainingStateId")
                                .HasColumnName("TrainingState_Id");

                            t.Property("TrainingTypeId")
                                .HasColumnName("TrainingType_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingEntitlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DurationHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<string>("SeasonCategoryName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.Property<int>("TrainingPhaseId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TrainingEntitlement", "sport", t =>
                        {
                            t.Property("SeasonCategoryName")
                                .HasColumnName("SeasonCategory_Name");

                            t.Property("SeasonId")
                                .HasColumnName("SeasonCategory_Season_Id");

                            t.Property("TrainingPhaseId")
                                .HasColumnName("TrainingPhase_Id");

                            t.Property("TrainingTypeId")
                                .HasColumnName("TrainingType_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TrainingPhase", "sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Přípravné období"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Předzávodní období"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Závodní období"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Přechodné (regenerační) období"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("DurationMinutes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(datediff(minute,[TimeFrom],[TimeTo]))", true);

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeasonCategoryName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("TimeTo")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.Property<int>("TrainingPhaseId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TrainingPlan", "sport", t =>
                        {
                            t.Property("SeasonCategoryName")
                                .HasColumnName("SeasonCategory_Name");

                            t.Property("SeasonId")
                                .HasColumnName("SeasonCategory_Season_Id");

                            t.Property("TrainingPhaseId")
                                .HasColumnName("TrainingPhase_Id");

                            t.Property("TrainingTypeId")
                                .HasColumnName("TrainingType_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TrainingState", "sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Plán"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Potvrzený KIS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jen KIS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Změna času"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Zrušený"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Změna termínu"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Porucha ZS"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TrainingType", "sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Suchá příprava"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Led"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.CoachTraining", b =>
                {
                    b.HasOne("SportSys.Database.Models.dboSchema.Coach", "Coach")
                        .WithMany("CoachTrainings")
                        .HasForeignKey("CoachId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.ParticipationType", "ParticipationType")
                        .WithMany("CoachTrainings")
                        .HasForeignKey("ParticipationTypeId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.Training", "Training")
                        .WithMany("CoachTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("ParticipationType");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.CoachTrainingEntitlement", b =>
                {
                    b.HasOne("SportSys.Database.Models.dboSchema.Coach", "Coach")
                        .WithMany("CoachTrainingEntitlementCoaches")
                        .HasForeignKey("CoachId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.dboSchema.CoachRole", "CoachRole")
                        .WithMany("CoachTrainingEntitlementCoachRoles")
                        .HasForeignKey("CoachRoleId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingEntitlement", "TrainingEntitlement")
                        .WithMany("CoachTrainingEntitlements")
                        .HasForeignKey("TrainingEntitlementId")
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("CoachRole");

                    b.Navigation("TrainingEntitlement");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.CoachTrainingPlan", b =>
                {
                    b.HasOne("SportSys.Database.Models.dboSchema.Coach", "Coach")
                        .WithMany("CoachTrainingPlans")
                        .HasForeignKey("CoachId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingPlan", "TrainingPlan")
                        .WithMany("CoachTrainingPlans")
                        .HasForeignKey("TrainingPlanId")
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.Match", b =>
                {
                    b.HasOne("SportSys.Database.Models.sportSchema.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.IceRink", "IceRink")
                        .WithMany("Matches")
                        .HasForeignKey("IceRinkId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.MatchType", "MatchType")
                        .WithMany("Matches")
                        .HasForeignKey("MatchTypeId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.SeasonCategory", "SeasonCategory")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId", "SeasonCategoryName")
                        .IsRequired();

                    b.OwnsOne("SportSys.Database.Models.sportSchema.MatchResult", "Result", b1 =>
                        {
                            b1.Property<int>("MatchId")
                                .ValueGeneratedOnAdd();

                            b1.Property<int?>("AwayGoals");

                            b1.Property<int?>("HomeGoals");

                            b1.HasKey("MatchId");

                            b1.ToTable("Match", "sport", t =>
                                {
                                    t.Property("MatchId")
                                        .HasColumnName("Match_Id");
                                });

                            b1
                                .ToJson("Result")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("IceRink");

                    b.Navigation("MatchType");

                    b.Navigation("Result");

                    b.Navigation("Season");

                    b.Navigation("SeasonCategory");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.SeasonCategory", b =>
                {
                    b.HasOne("SportSys.Database.Models.sportSchema.Season", "Season")
                        .WithMany("SeasonCategories")
                        .HasForeignKey("SeasonId")
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.Team", b =>
                {
                    b.HasOne("SportSys.Database.Models.sportSchema.IceRink", "HomeIceRink")
                        .WithMany("Teams")
                        .HasForeignKey("HomeIceRinkId");

                    b.Navigation("HomeIceRink");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.Training", b =>
                {
                    b.HasOne("SportSys.Database.Models.sportSchema.Season", "Season")
                        .WithMany("Training")
                        .HasForeignKey("SeasonId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingPhase", "TrainingPhase")
                        .WithMany("Training")
                        .HasForeignKey("TrainingPhaseId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingPlan", "TrainingPlan")
                        .WithMany("Training")
                        .HasForeignKey("TrainingPlanId");

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingState", "TrainingState")
                        .WithMany("Training")
                        .HasForeignKey("TrainingStateId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingType", "TrainingType")
                        .WithMany("Training")
                        .HasForeignKey("TrainingTypeId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.SeasonCategory", "SeasonCategory")
                        .WithMany("Training")
                        .HasForeignKey("SeasonId", "SeasonCategoryName")
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("SeasonCategory");

                    b.Navigation("TrainingPhase");

                    b.Navigation("TrainingPlan");

                    b.Navigation("TrainingState");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingEntitlement", b =>
                {
                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingPhase", "TrainingPhase")
                        .WithMany("TrainingEntitlements")
                        .HasForeignKey("TrainingPhaseId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingType", "TrainingType")
                        .WithMany("TrainingEntitlements")
                        .HasForeignKey("TrainingTypeId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.SeasonCategory", "SeasonCategory")
                        .WithMany("TrainingEntitlements")
                        .HasForeignKey("SeasonId", "SeasonCategoryName")
                        .IsRequired();

                    b.Navigation("SeasonCategory");

                    b.Navigation("TrainingPhase");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingPlan", b =>
                {
                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingPhase", "TrainingPhase")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("TrainingPhaseId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingType", "TrainingType")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("TrainingTypeId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.SeasonCategory", "SeasonCategory")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("SeasonId", "SeasonCategoryName")
                        .IsRequired();

                    b.Navigation("SeasonCategory");

                    b.Navigation("TrainingPhase");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("SportSys.Database.Models.dboSchema.Coach", b =>
                {
                    b.Navigation("CoachTrainingEntitlementCoaches");

                    b.Navigation("CoachTrainingPlans");

                    b.Navigation("CoachTrainings");
                });

            modelBuilder.Entity("SportSys.Database.Models.dboSchema.CoachRole", b =>
                {
                    b.Navigation("CoachTrainingEntitlementCoachRoles");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.IceRink", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.MatchType", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.ParticipationType", b =>
                {
                    b.Navigation("CoachTrainings");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.Season", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("SeasonCategories");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.SeasonCategory", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Training");

                    b.Navigation("TrainingEntitlements");

                    b.Navigation("TrainingPlans");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.Training", b =>
                {
                    b.Navigation("CoachTrainings");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingEntitlement", b =>
                {
                    b.Navigation("CoachTrainingEntitlements");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingPhase", b =>
                {
                    b.Navigation("Training");

                    b.Navigation("TrainingEntitlements");

                    b.Navigation("TrainingPlans");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingPlan", b =>
                {
                    b.Navigation("CoachTrainingPlans");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingState", b =>
                {
                    b.Navigation("Training");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingType", b =>
                {
                    b.Navigation("Training");

                    b.Navigation("TrainingEntitlements");

                    b.Navigation("TrainingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
