// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;
using MatchType = SportSys.Database.Models.sportSchema.MatchType;

namespace SportSys.Database.Models;

public partial class HockeyContext : DbContext
{
    public HockeyContext(DbContextOptions<HockeyContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Coach> Coaches { get; set; }

    public virtual DbSet<CoachRole> CoachRoles { get; set; }

    public virtual DbSet<CoachTraining> CoachTrainings { get; set; }

    public virtual DbSet<CoachTrainingEntitlement> CoachTrainingEntitlements { get; set; }

    public virtual DbSet<CoachTrainingPlan> CoachTrainingPlans { get; set; }

    public virtual DbSet<IceRink> IceRinks { get; set; }

    public virtual DbSet<Match> Matches { get; set; }

    public virtual DbSet<MatchType> MatchTypes { get; set; }

    public virtual DbSet<Opponent> Opponents { get; set; }

    public virtual DbSet<ParticipationType> ParticipationTypes { get; set; }

    public virtual DbSet<Season> Seasons { get; set; }

    public virtual DbSet<SeasonCategory> SeasonCategories { get; set; }

    public virtual DbSet<Training> Training { get; set; }

    public virtual DbSet<TrainingEntitlement> TrainingEntitlements { get; set; }

    public virtual DbSet<TrainingPhase> TrainingPhases { get; set; }

    public virtual DbSet<TrainingPlan> TrainingPlans { get; set; }

    public virtual DbSet<TrainingState> TrainingStates { get; set; }

    public virtual DbSet<TrainingType> TrainingTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Sdílená sekvence pro Training.Id a Match.Id (TPC vzor na úrovni DB)
        modelBuilder.HasSequence<int>("SportEventSeq", "sport").StartsAt(2022L);

        // Veškerá konfigurace entit je v IEntityTypeConfiguration<T> třídách v Configurations/
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(HockeyContext).Assembly);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}