// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SportSys.Database.Models.dboSchema;
using SportSys.Database.Models.sportSchema;
using MatchType = SportSys.Database.Models.sportSchema.MatchType;

namespace SportSys.Database.Models;

public partial class HockeyContext : DbContext
{
    public HockeyContext(DbContextOptions<HockeyContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Coach> Coaches { get; set; }

    public virtual DbSet<CoachRole> CoachRoles { get; set; }

    public virtual DbSet<CoachTraining> CoachTrainings { get; set; }

    public virtual DbSet<CoachTrainingEntitlement> CoachTrainingEntitlements { get; set; }

    public virtual DbSet<CoachTrainingPlan> CoachTrainingPlans { get; set; }

    public virtual DbSet<IceRink> IceRinks { get; set; }

    public virtual DbSet<Match> Matches { get; set; }

    public virtual DbSet<MatchType> MatchTypes { get; set; }

    public virtual DbSet<Opponent> Opponents { get; set; }

    public virtual DbSet<ParticipationType> ParticipationTypes { get; set; }

    public virtual DbSet<Season> Seasons { get; set; }

    public virtual DbSet<SeasonCategory> SeasonCategories { get; set; }

    public virtual DbSet<Training> Training { get; set; }

    public virtual DbSet<TrainingEntitlement> TrainingEntitlements { get; set; }

    public virtual DbSet<TrainingPhase> TrainingPhases { get; set; }

    public virtual DbSet<TrainingPlan> TrainingPlans { get; set; }

    public virtual DbSet<TrainingState> TrainingStates { get; set; }

    public virtual DbSet<TrainingType> TrainingTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Coach>(entity =>
        {
            entity.Property(e => e.FullName).HasComputedColumnSql("(([FirstName]+N' ')+[LastName])", true);
        });

        modelBuilder.Entity<CoachTraining>(entity =>
        {
            entity.Property(e => e.Note).HasDefaultValue("", "DF_CoachTraining_Note");

            entity.HasOne(d => d.Coach).WithMany(p => p.CoachTrainings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CoachTraining_Coach");

            entity.HasOne(d => d.ParticipationType).WithMany(p => p.CoachTrainings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CoachTraining_ParticipationType");
        });

        modelBuilder.Entity<CoachTrainingEntitlement>(entity =>
        {
            entity.HasOne(d => d.CoachRole).WithMany(p => p.CoachTrainingEntitlementCoachRoles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CoachTrainingEntitlement_CoachRole");

            entity.HasOne(d => d.Coach).WithMany(p => p.CoachTrainingEntitlementCoaches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CoachTrainingEntitlement_Coach");

            entity.HasOne(d => d.TrainingEntitlement).WithMany(p => p.CoachTrainingEntitlements)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CoachTrainingEntitlement_TrainingEntitlement");
        });

        modelBuilder.Entity<CoachTrainingPlan>(entity =>
        {
            entity.HasOne(d => d.Coach).WithMany(p => p.CoachTrainingPlans)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CoachTrainingPlan_Coach");

            entity.HasOne(d => d.TrainingPlan).WithMany(p => p.CoachTrainingPlans)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CoachTrainingPlan_TrainingPlan");
        });

        modelBuilder.Entity<Match>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(NEXT VALUE FOR [sport].[SportEventSeq])", "DF__Match__Id");
            entity.Property(e => e.DurationMinutes).HasComputedColumnSql("(datediff(minute,[TimeFrom],[TimeTo]))", true);

            entity.HasOne(d => d.IceRink).WithMany(p => p.Matches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_IceRink");

            entity.HasOne(d => d.MatchType).WithMany(p => p.Matches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_MatchType");

            entity.HasOne(d => d.Opponent).WithMany(p => p.Matches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_Opponent");

            entity.HasOne(d => d.Season).WithMany(p => p.Matches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_Season");

            entity.HasOne(d => d.SeasonCategory).WithMany(p => p.Matches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_SeasonCategory");
        });

        modelBuilder.Entity<Opponent>(entity =>
        {
            entity.HasOne(d => d.HomeIceRink).WithMany(p => p.Opponents).HasConstraintName("FK_Opponent_IceRink");
        });

        modelBuilder.Entity<ParticipationType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ParticipationType ");
        });

        modelBuilder.Entity<SeasonCategory>(entity =>
        {
            entity.Property(e => e.BirthYears).HasDefaultValue("[]", "DF_SeasonCategory_BirthYears");

            entity.HasOne(d => d.Season).WithMany(p => p.SeasonCategories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Category_Season");
        });

        modelBuilder.Entity<Training>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(NEXT VALUE FOR [sport].[SportEventSeq])", "DF_Training_Id");
            entity.Property(e => e.DurationMinutes).HasComputedColumnSql("(datediff(minute,[TimeFrom],[TimeTo]))", true);

            entity.HasOne(d => d.IceRink).WithMany(p => p.Trainings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Training_IceRink");

            entity.HasOne(d => d.Season).WithMany(p => p.Training)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Training_Season");

            entity.HasOne(d => d.TrainingPhase).WithMany(p => p.Training)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Training_TrainingPhase");

            entity.HasOne(d => d.TrainingPlan).WithMany(p => p.Training).HasConstraintName("FK_Training_TrainingPlan");

            entity.HasOne(d => d.TrainingState).WithMany(p => p.Training)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Training_TrainingState");

            entity.HasOne(d => d.TrainingType).WithMany(p => p.Training)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Training_TrainingType");

            entity.HasOne(d => d.SeasonCategory).WithMany(p => p.Training)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Training_SeasonCategory");
        });

        modelBuilder.Entity<TrainingEntitlement>(entity =>
        {
            entity.HasOne(d => d.TrainingPhase).WithMany(p => p.TrainingEntitlements)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TrainingEntitlement_TrainingPhase");

            entity.HasOne(d => d.TrainingType).WithMany(p => p.TrainingEntitlements)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TrainingEntitlement_TrainingType");

            entity.HasOne(d => d.SeasonCategory).WithMany(p => p.TrainingEntitlements)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TrainingEntitlement_SeasonCategory");
        });

        modelBuilder.Entity<TrainingPhase>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Phase");
        });

        modelBuilder.Entity<TrainingPlan>(entity =>
        {
            entity.Property(e => e.DurationMinutes).HasComputedColumnSql("(datediff(minute,[TimeFrom],[TimeTo]))", true);

            entity.HasOne(d => d.TrainingPhase).WithMany(p => p.TrainingPlans)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TrainingPlan_TrainingPhase");

            entity.HasOne(d => d.TrainingType).WithMany(p => p.TrainingPlans)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TrainingPlan_TrainingType");

            entity.HasOne(d => d.SeasonCategory).WithMany(p => p.TrainingPlans)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TrainingPlan_SeasonCategory");
        });
        modelBuilder.HasSequence<int>("SportEventSeq", "sport").StartsAt(2022L);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}